// Code generated by MockGen. DO NOT EDIT.
// Source: internal/message/validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	gcloud_grpc_boilerplate "github.com/micromaniacs/gcloud-grpc-boilerplate"
	message "github.com/micromaniacs/gcloud-grpc-boilerplate/internal/message"
	reflect "reflect"
)

// MockValidator is a mock of Validator interface
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateGetByID mocks base method
func (m *MockValidator) ValidateGetByID(arg0 *gcloud_grpc_boilerplate.GetByIDRequest) (message.GetByIDInput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateGetByID", arg0)
	ret0, _ := ret[0].(message.GetByIDInput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateGetByID indicates an expected call of ValidateGetByID
func (mr *MockValidatorMockRecorder) ValidateGetByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateGetByID", reflect.TypeOf((*MockValidator)(nil).ValidateGetByID), arg0)
}

// ValidateCreate mocks base method
func (m *MockValidator) ValidateCreate(arg0 *gcloud_grpc_boilerplate.CreateRequest) (message.CreateInput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCreate", arg0)
	ret0, _ := ret[0].(message.CreateInput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateCreate indicates an expected call of ValidateCreate
func (mr *MockValidatorMockRecorder) ValidateCreate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCreate", reflect.TypeOf((*MockValidator)(nil).ValidateCreate), arg0)
}
